service: AuthServer

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  timeout: 30
  environment:
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}
    NODE_ENV: production
    REDIRECT_URI_PRODUCTION: https://circle-up-brown.vercel.app
    REDIRECT_URI_LOCAL: http://localhost:3000

functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: api/get-auth-url
          method: get
          cors:
            origins:
              - http://localhost:3000
              - https://circle-up-brown.vercel.app
            headers:
              - Content-Type
              - Authorization

  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: api/get-access-token
          method: post
          cors: true

  getCalendarEvents:
    handler: handler.getCalendarEvents
    events:
      - http:
          path: api/get-events/{access_token}
          method: get
          cors: true

  revoke:
    handler: authServer/revoke.revoke
    events:
      - http:
          path: revoke
          method: post
          cors: true
